---

name: autocommit

on: push

jobs:
  format-code:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:

    - uses: actions/checkout@v2

    - name: Run Git Auto Commit
      id: auto-commit-action
      uses: stefanzweifel/git-auto-commit-action@v5
      with:
        commit_message: Automated Change

    - name: Run if changes have been detected
      if: steps.auto-commit-action.outputs.changes_detected == 'true'
      run: go run -e 'fmt.Println("Changes!")'

    - name: Run if no changes have been detected
      if: steps.auto-commit-action.outputs.changes_detected == 'false'
      run: go run -e 'fmt.Println("No Changes!")'

      
